### PR TITLE
feat(blog): add clap button for blog posts

### PR DESCRIPTION
**Pull request by NickyMeuleman**
Investigate how https://medium.com/@ColinEberhardt/free-claps-for-everyone-a-medium-style-applause-button-a6f3082a5c0e works

Thank you @ColinEberhardt!

notes:
sometimes it's invisible
image
Can't get it to display again now.

In Firefox: repeated loading:

When it is visible, claps are the same across all blog-posts even if I didn't visit them yet.

Possible solution: build own frontend and use the API the button uses
https://reactjs.org/docs/faq-ajax.html

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
> Thank you @ColinEberhardt!

No problem!

> sometimes it's invisible

Is there any way you can provide a repo / example I can take a look at?

> When it is visible, claps are the same across all blog-posts even if I didn't visit them yet.

The applause API uses the HTTP referrer to determine which page the clap count is being requested for. However, you can provide an explicit url, e.g.

```
<applause-button url="google.com" />
```

I'll see if I can find your requests in the logs. Again, if you have a preview build I could take a look at I'd be happy to investigate.

**Comment by NickyMeuleman** [comment]
I'm having fun digging into your code :).

a preview for this PR is here: https://deploy-preview-10--nickymeuleman.netlify.com/

**Comment by ColinEberhardt** [comment]
The applause button is a custom element, which fetches the current clap count within the `connectedCallback` lifecyle event, which occurs when the "custom element is appended into a document-connected element".

With your blog, when you navigate between posts, this lifecycle event is not called.

I could add a method to the button to allow you to 'force' it to update the count based on the updated document URL.

**Comment by NickyMeuleman** [comment]
> When it is visible, claps are the same across all blog-posts even if I didn't visit them yet.

What probably happened: React didn't destroy the element and create a new one when moving between pages, but kept the existing one.

That would also explain:
> With your blog, when you navigate between posts, this lifecycle event is not called.

Solved this in #11 by adding a `key` property to the React-Component, forcing it to be destroyed and rebuilt when you navigate to another page. I'll try that on this one too, but since it's a custom-element and not a React-Components, I'm not sure if it'll work.

**Comment by NickyMeuleman** [comment]
Closing this one, made a React component that calls the API.

**Pull request closed without merging**
